permalink: /:title/
url: http://quarkxie.github.io
name: Qiuchen Xie
author: Qiuchen Xie
email: qiuchen.xie@gmail.com
github: quarkxie
pygments: true
safe: true
paginate: 20
about: "under construction"
